/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using Thrift;
using Thrift.Collections;
using System.Runtime.Serialization;
using Thrift.Protocol;
using Thrift.Transport;

namespace ThriftApp.Lib
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class AppResource : TBase
  {
    private string _AppCode;
    private string _Scope;
    private string _ResourceCode;

    public string AppCode
    {
      get
      {
        return _AppCode;
      }
      set
      {
        __isset.AppCode = true;
        this._AppCode = value;
      }
    }

    public string Scope
    {
      get
      {
        return _Scope;
      }
      set
      {
        __isset.Scope = true;
        this._Scope = value;
      }
    }

    public string ResourceCode
    {
      get
      {
        return _ResourceCode;
      }
      set
      {
        __isset.ResourceCode = true;
        this._ResourceCode = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool AppCode;
      public bool Scope;
      public bool ResourceCode;
    }

    public AppResource() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.String) {
                AppCode = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                Scope = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.String) {
                ResourceCode = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("AppResource");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (AppCode != null && __isset.AppCode) {
          field.Name = "AppCode";
          field.Type = TType.String;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(AppCode);
          oprot.WriteFieldEnd();
        }
        if (Scope != null && __isset.Scope) {
          field.Name = "Scope";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(Scope);
          oprot.WriteFieldEnd();
        }
        if (ResourceCode != null && __isset.ResourceCode) {
          field.Name = "ResourceCode";
          field.Type = TType.String;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(ResourceCode);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("AppResource(");
      bool __first = true;
      if (AppCode != null && __isset.AppCode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AppCode: ");
        __sb.Append(AppCode);
      }
      if (Scope != null && __isset.Scope) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Scope: ");
        __sb.Append(Scope);
      }
      if (ResourceCode != null && __isset.ResourceCode) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ResourceCode: ");
        __sb.Append(ResourceCode);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
